version: "3.9"
services:
  fido2server:
    build: ./fido2server
    image: darkedges/fido2server_base
  openldap:
    build: ./openldap
    image: darkedges/f2s_openldap
    container_name: openldap
    networks:
      - f2s
    depends_on:
      - "fido2server"
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_SKIP_DEFAULT_TREE=yes
      - LDAP_ROOT=dc=strongauth,dc=com
      - LDAP_ADMIN_USERNAME=Manager
      - LDAP_ADMIN_PASSWORD=Abcd1234!
      - LDAP_CUSTOM_SCHEMA_FILE=/tmp/fido2server/local.ldif
    volumes:
      - 'openldap_data:/bitnami/openldap'
  mariadb:
    build: ./mariadb
    image: darkedges/f2s_mariadb
    container_name: mariadb
    networks:
      - f2s
    depends_on:
      - "openldap"
    environment:
      - MARIADB_ROOT_PASSWORD=BigKahuna
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=BigKahuna
      - MARIADB_USER=skfsdbuser
      - MARIADB_PASSWORD=AbracaDabra
      - MARIADB_DATABASE=skfs
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    # glassfish:
    #   build: ./glassfish
    #   image: darkedges/f2s_glassfish
    #   container_name: glassfish
    #   networks:
    #     - f2s
    #   depends_on:
    #     - "fido2server"

volumes:
  openldap_data:
    driver: local
  mariadb_data:
    driver: local
networks:
  f2s:
    driver: bridge
