version: "3.9"
services:
  fido2server:
    build: ./fido2server
    image: darkedges/fido2server_base
  openldap:
    build: ./openldap
    image: darkedges/f2s_openldap
    container_name: openldap
    networks:
      - f2s
    depends_on:
      - "fido2server"
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_SKIP_DEFAULT_TREE=yes
      - LDAP_ROOT=dc=strongauth,dc=com
      - LDAP_ADMIN_USERNAME=Manager
      - LDAP_ADMIN_PASSWORD=Abcd1234!
      - LDAP_CUSTOM_SCHEMA_FILE=/tmp/fido2server/local.ldif
    volumes:
      - 'openldap_data:/bitnami/openldap'
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
  mariadb:
    build: ./mariadb
    image: darkedges/f2s_mariadb
    container_name: mariadb
    networks:
      - f2s
    environment:
      - MARIADB_ROOT_PASSWORD=BigKahuna
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=BigKahuna
      - MARIADB_USER=skfsdbuser
      - MARIADB_PASSWORD=AbracaDabra
      - MARIADB_DATABASE=skfs
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
  glassfish:
    build: ./glassfish
    image: darkedges/f2s_glassfish
    container_name: glassfish
    networks:
      - f2s
    depends_on:
      mariadb:
        condition: service_healthy
      openldap:
        condition: service_healthy

    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=newpass
      - POSTBOOT_COMMANDS=/usr/local/strongkey/scripts/post-boot-commands.asadmin
      - PREBOOT_COMMANDS=/usr/local/strongkey/scripts/pre-boot-commands.asadmin
    ports:
      - '8080:8080'
      - '4848:4838'

volumes:
  openldap_data:
    driver: local
  mariadb_data:
    driver: local
networks:
  f2s:
    driver: bridge
